const LOAD_GAMES = "LOAD_GAMES";
const FILTER = "FILTER";
const ORDER = "ORDER";
const LOAD_GENRES = "LOAD_GENRES";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
//Falta paginar

export { LOAD_GAMES, FILTER, ORDER, LOAD_GENRES, SEARCH_BY_NAME };
